### ISSUE TITLE
`:simple_one_for_one` strategy deprecation warning in Elixir 1.10

### ISSUE THREAD

**Issue by hoyon** [bitwalker/libring#20]
When running an app which uses libring in Elixir 1.10 I get the following deprecation message:

```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.0) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.0) lib/supervisor.ex:556: Supervisor.start_link/2
  (libring 1.4.0) lib/app.ex:13: HashRing.App.start/2
  (kernel 6.5.1) application_master.erl:277: :application_master.start_it_old/4
```

**Comment by kitplummer** [comment]
This is great.  Ok, now to update swarm.  :D
